variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  BRANCH_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - lint
  - test
  - build
  - integration
  - release

.python-template: &python-template
  image: python:3.5
  before_script:
    - pip install .[dev]

lint:
  <<: *python-template
  stage: lint
  script:
    - make lint

unit:
  <<: *python-template
  stage: test
  script:
    - make test/unit

provisioners:
  <<: *python-template
  stage: test
  script:
    - make test/provisioners

build-wheel:
  <<: *python-template
  stage: build
  script:
    - make build/wheel
  artifacts:
    paths:
      - dist/*.whl

.docker-template: &docker-template
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

integration:
  <<: *docker-template
  stage: integration
  script:
    - make test/integration

integration-long:
  <<: *docker-template
  stage: integration
  script:
    - make test/integration_long
