stages:
  - lint
  - test
  - build
  - integration
  - release

# linting
.python-template: &python-template
  image: python:3.5
  before_script:
    - pip install .[dev]

lint:
  <<: *python-template
  stage: lint
  script:
    - make lint
  artifacts:
    reports:
      junit: build/mypy.xml

# unit-style tests
unit:
  <<: *python-template
  stage: test
  script:
    - make test/unit
  artifacts:
    reports:
      junit: build/test.xml

provisioners:
  <<: *python-template
  stage: test
  script:
    - make test/provisioners
  artifacts:
    reports:
      junit: build/test.xml

# package
build-wheel:
  <<: *python-template
  stage: build
  script:
    - make build/wheel RELEASE_VERSION=$(echo $CI_COMMIT_TAG | sed -e s/^v//)
  artifacts:
    paths:
      - dist/*.whl

# integration tests
.docker-template: &docker-template
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

integration:
  <<: *docker-template
  stage: integration
  script:
    - make test/integration
  artifacts:
    reports:
      junit: build/test.xml

integration-long:
  <<: *docker-template
  stage: integration
  script:
    - make test/integration_long
  artifacts:
    reports:
      junit: build/test.xml

# release
release-test:
  <<: *python-template
  stage: release
  when: manual
  variables:
    TWINE_USERNAME: $PYPI_TEST_USERNAME
    TWINE_PASSWORD: $PYPI_TEST_PASSWORD
  environment:
    name: test.pypi.org
    url: https://test.pypi.org/project/deploy-ostree
  script:
    - make release/test

release-pypi:
  <<: *python-template
  stage: release
  only:
    - /^v.+$/
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  environment:
    name: pypi.org
    url: https://pypi.org/project/deploy-ostree
  script:
    - make release/pypi
