variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

stages:
  - lint
  - test
  - build
  - integration

.python-template: &python-template
  image: python:3.5
  before_script:
    - pip install .[dev]

lint:
  <<: *python-template
  stage: lint
  script:
    - flake8 .
    - mypy .

unit:
  <<: *python-template
  stage: test
  script:
    - python3 -m unittest discover -v -t . -s tests/unit

provisioners:
  <<: *python-template
  stage: test
  script:
    - python3 -m unittest discover -v -t . -s tests/unit

.docker-template: &docker-template
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  <<: *docker-template
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

integration:
  <<: *docker-template
  stage: integration
  script:
    - docker run --rm -i --privileged -v /ostree -v $PWD/tests:/tests $IMAGE_TAG python3 -m unittest discover -v -t / -s /tests/integration

integration-long:
  <<: *docker-template
  stage: integration
  script:
    - docker run --rm -i --privileged -v /ostree -v $PWD/tests:/tests $IMAGE_TAG python3 -m unittest discover -v -t / -s /tests/integration_long
