FROM debian:9-slim
RUN apt-get update && \
    apt-get install -y \
        make \
        ostree \
        python3 \
        python3-pip \
        python3-setuptools
RUN pip3 install flake8 mypy

ADD . /package
WORKDIR /package
CMD ["make", "qc/host"]
