FROM debian:9-slim
RUN apt-get update && \
    apt-get install -y \
        make \
        python3 \
        python3-pip \
        python3-setuptools
# stretch ostree is too old to work well so we get a backport
RUN echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/stretch-backports.list && \
    apt-get update && \
    apt-get install -t stretch-backports -y ostree
RUN pip3 install flake8 mypy

ADD . /package
WORKDIR /package
CMD ["make", "qc/host"]
