FROM debian:9-slim
RUN apt-get update && \
    apt-get install -y \
        make \
        ostree \
        python3 \
        python3-pip \
        python3-setuptools

ADD . /package
WORKDIR /package
RUN pip3 install .[dev]

CMD ["make", "qc/host"]
