#!/bin/sh
# Copyright 2018 Felix Krull
# Licensed under the MIT license, see LICENSE for details.
set -eu

chroot $1 useradd -M ${DEPLOY_OSTREE_username}
echo ${DEPLOY_OSTREE_username}:${DEPLOY_OSTREE_password} | chroot $1 chpasswd
